### ISSUE TITLE
Crear descripcion de variantes

### ISSUE THREAD

**Issue by nicomendez** [nicomendez/UNR-EC-2017-g05#1]
Crear un pdf con un breve descripcion de las variantes propuestas a iCrash

**Comment by nicomendez** [comment]
[Descripcion_Variantes.pdf](https://github.com/nicomendez/Excalibur/files/1317579/Descripcion_Variantes.pdf)

**Comment by acapozucca** [comment]
PI variant:
Por qué el chequear que las coordenadas del nuevo PI estén "al menos 5 metros de las anteriormente cargadas"? 
Interesante presentación de los casos de uso. Hay que reever las validaciones antes de dar de alta un PI.
Falta indicar las funcionalidades que permiten hacer uso de los PI por parte del administrador.

**Comment by acapozucca** [comment]
Max tries variant:
Cómo se computa que el usuario intentó loguearse 3 veces sin éxito? Son simplemente intentos consecutivos, o se tiene en cuenta un rango temporal?
Cómo se resuelve un captcha? Cuáles son los parámetros de entrada para computar la resolución del captcha?
Cuál es el orden para permitir al usuario loguearse: captcha correcto y luego contraseña correcta, al revés, o en cualquier orden? 
Cómo se continúa luego de un cambio de contraseña?
